name: Artia Promotions
favicon: null
layout_spectrum: 0.9136144588701427
typography_spectrum: 0.4518167299684137
title: Artia Promotions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eb9e4e'
    - '#5b4d4a'
    - '#eedb75'
    - '#d47c47'
    - '#4f2806'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
